"use client";
import {useState} from 'react';
import {languageRequest} from '../app/control/models/language/actions';
type Mode='local'|'lan'|'cloud';
type Profile={mode:Mode;protocol:'ollama'|'openai';base_url:string;model:string;timeout_seconds:number;enabled:boolean;secret_ref:string|null};
export type LanguageConfiguration={active_mode:Mode;profiles:Profile[];credentials:Record<string,boolean>;allowed_origins:string[]};
const names={local:'Mac 本地',lan:'局域网服务器',cloud:'云端 API'};
export default function LanguageSettings({initial}:{initial:LanguageConfiguration}){
 const [config,setConfig]=useState(initial),[selected,setSelected]=useState<Mode>(initial.active_mode),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const p=config.profiles.find(p=>p.mode===selected)!;
 function update(value:Partial<Profile>){setConfig(old=>({...old,profiles:old.profiles.map(p=>p.mode===selected?{...p,...value}:p)}));setMessage('配置已修改，保存后生效。');}
 async function save(test=false){setBusy(true);setMessage('');try{const saved=await languageRequest('/admin/llm',{active_mode:config.active_mode,profiles:config.profiles},'PUT');if(saved.error){setMessage(saved.error);return;}if(test){const result=await languageRequest('/admin/llm/test',{mode:selected});setMessage(result.error??`${result.data.status==='healthy'?'连接正常，结构化输出验证通过':'响应异常'} · ${result.data.runtime_ms} ms · ${result.data.model}`);}else setMessage('语言模型配置已保存。');}finally{setBusy(false);}}
 return <><header className="console-heading"><div><h1>语言模型助手</h1><p>自然语言生成任务草案，确认后调用现有提取流程</p></div><span className="badge">默认本地 · 手动流程始终可用</span></header><div className="resource-master-detail"><aside className="resource-navigator"><h2>部署方式</h2>{(['local','lan','cloud'] as Mode[]).map(mode=><button className="resource-choice secondary" aria-pressed={selected===mode} disabled={busy} key={mode} onClick={()=>setSelected(mode)}>{names[mode]}{config.active_mode===mode?' · 当前使用':''}</button>)}<p className="muted">三种配置分别保留，不自动跨环境回退。</p></aside><section className="resource-detail"><h2>{names[selected]}</h2><form onSubmit={e=>{e.preventDefault();void save();}}>{message&&<p role="status" className="notice">{message}</p>}<label className="inline-check"><input type="checkbox" checked={config.active_mode===selected} disabled={busy} onChange={()=>setConfig(old=>({...old,active_mode:selected}))}/>将此方式设为当前使用</label><label className="inline-check"><input type="checkbox" checked={p.enabled} disabled={busy} onChange={e=>update({enabled:e.target.checked})}/>启用语言助手</label>{selected==='local'?<p>原生 Ollama · 通过服务器端本地桥接调用。模型权重保留在本机，不随代码提交。</p>:<><label>协议<select value={p.protocol} disabled={busy} onChange={e=>update({protocol:e.target.value as Profile['protocol']})}><option value="ollama">Ollama</option><option value="openai">OpenAI 兼容接口</option></select></label><label>服务地址<input type="url" value={p.base_url} disabled={busy} onChange={e=>update({base_url:e.target.value})} placeholder={selected==='cloud'?'https://服务域名/v1':'http://局域网服务器:11434'}/></label><p className="muted">地址需先加入本地 .env 的 LLM_ALLOWED_ORIGINS 白名单；修改后重建 API 容器。不会自动访问未登记地址。</p><label>服务器端凭据<select value={p.secret_ref??''} disabled={busy} onChange={e=>update({secret_ref:e.target.value||null})}><option value="">无需凭据</option><option value="LLM_LAN_API_KEY">LLM_LAN_API_KEY</option><option value="LLM_CLOUD_API_KEY">LLM_CLOUD_API_KEY</option></select></label><small>{p.secret_ref?(config.credentials[p.secret_ref]?'凭据已配置（不会返回浏览器）':'请在本地 .env 配置此变量，然后重建 API'):'使用无凭据接口'}</small></>}<label>模型名称<input value={p.model} required disabled={busy} onChange={e=>update({model:e.target.value})}/></label><label>超时（秒）<input type="number" min={5} max={180} value={p.timeout_seconds} disabled={busy} onChange={e=>update({timeout_seconds:Number(e.target.value)})}/></label>{selected==='cloud'&&<p className="notice">云端可能产生费用。助手只发送指令和资源名称/标识，不发送影像、掩膜或平台凭据；每次规划前需用户同意。</p>}<div className="console-actions"><button disabled={busy}>{busy?'处理中…':'保存配置'}</button><button className="secondary" type="button" disabled={busy||!p.enabled} onClick={()=>void save(true)}>保存并测试连接</button></div></form><h3>能力范围</h3><p>读取资源、查看任务、生成单瓦片提取草案。LLM 不执行代码、不访问任意 URL、不创建虚构样例、不自动审核或删除数据。</p></section></div></>;
}
