"use client";
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import type {Project} from '../lib/session';
import {saveSettings,changeSettingsMember,type SettingsMember} from '../app/projects/[id]/settings-actions';
const roles:Record<string,string>={owner:'所有者',editor:'编辑者',viewer:'查看者'};
export default function ProjectSettings({initial,initialMembers,initialSection="general",embedded=false,hideNavigation=false,onSectionChange,onProjectSaved}:{initial:Project;initialMembers:SettingsMember[];initialSection?:string;embedded?:boolean;hideNavigation?:boolean;onSectionChange?:(section:string)=>void;onProjectSaved?:(project:Project)=>void}){
 const [project,setProject]=useState(initial),[members,setMembers]=useState(initialMembers);
 const tab=initialSection;
 const [name,setName]=useState(initial.name),[description,setDescription]=useState(initial.description),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const [dialogOpen,setDialogOpen]=useState(false);
 const [email,setEmail]=useState(''),[role,setRole]=useState('viewer'),[editing,setEditing]=useState<SettingsMember|null>(null),[removing,setRemoving]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null);const owner=project.my_role==='owner',editable=owner||project.my_role==='editor';
 const dirty=name!==project.name||description!==project.description;
 useEffect(()=>{window.dispatchEvent(new CustomEvent('workspace-settings-dirty',{detail:dirty}));return()=>{window.dispatchEvent(new CustomEvent('workspace-settings-dirty',{detail:false}));};},[dirty]);
 async function save(){setBusy(true);setError('');try{const result=await saveSettings(project.id,name,description);if(result.error)setError(result.error);else if(result.project){setProject(old=>({...old,...result.project}));setName(result.project.name);setDescription(result.project.description);setNotice('项目信息已更新');onProjectSaved?.({...project,...result.project});}}finally{setBusy(false);}}
 function open(member:SettingsMember|null,remove=false){setEditing(member);setRemoving(remove);setRole(member?.role??'viewer');setEmail('');setError('');setDialogOpen(true);dialog.current?.showModal();}
 async function submitMember(){setBusy(true);setError('');try{const result=await changeSettingsMember(project.id,editing?(removing?'remove':'change'):'add',editing?.user_id??email,role);if(result.error)setError(result.error);else if(result.members){setMembers(result.members);dialog.current?.close();setNotice(editing?(removing?'成员已移除':'成员角色已更新'):'成员已加入项目');}}finally{setBusy(false);}}
 return <section className={`project-settings ${embedded?'embedded-settings':''}`}>{!embedded&&<><nav className="project-breadcrumb" aria-label="当前位置"><Link href="/control/projects">所有项目</Link><span>/</span><Link href={`/projects/${project.id}/workspace`}>{project.name}</Link><span>/ 项目设置</span></nav><header className="project-settings-heading"><div><h1>{project.name} <span className="badge">{roles[project.my_role]}</span></h1><p>项目设置</p></div><Link className="settings-workspace-cta" href={`/projects/${project.id}/workspace`}>返回工作区</Link></header></>}<div className="project-settings-shell">{!hideNavigation&&<nav aria-label="项目设置">{[['general','常规'],['members','成员与权限'],['danger','危险操作']].map(([id,label])=>embedded?<button key={id} aria-current={tab===id?'page':undefined} onClick={()=>onSectionChange?.(id)}>{label}</button>:<Link key={id} aria-current={tab===id?'page':undefined} href={`/projects/${project.id}/settings${id==='general'?'':'/'+id}`}>{label}</Link>)}</nav>}<div className="project-settings-content">{notice&&<div className="settings-toast" role="status">{notice}<button type="button" aria-label="关闭通知" onClick={()=>setNotice('')}>×</button></div>}{error&&!dialogOpen&&<p role="alert">{error}</p>}
 {tab==='general'&&<><h2>常规</h2><form onSubmit={e=>{e.preventDefault();void save();}}><label>项目名称<input value={name} onChange={e=>setName(e.target.value)} required maxLength={120} disabled={!editable||busy}/></label><label>项目描述<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="描述项目目标，帮助团队理解工作内容" rows={4} maxLength={2000} disabled={!editable||busy}/></label><dl><dt>所有者</dt><dd>{members.find(m=>m.role==='owner')?.email??'账号信息不可用'}</dd><dt>创建时间</dt><dd>{new Date(project.created_at).toLocaleDateString('zh-CN')}</dd></dl><details><summary>开发者详情</summary><p>项目标识</p><code>{project.id}</code></details>{editable&&<button className="secondary" disabled={!dirty||!name.trim()||busy}>{busy?'正在保存…':'保存更改'}</button>}</form></>}
 {tab==='members'&&<><div className="settings-section-title"><h2>成员与权限</h2>{owner&&<button className="secondary compact" onClick={()=>open(null)}>添加成员</button>}</div><p className="muted">通过邮箱添加已有本地账号；加入后即可访问项目，无需邮件邀请。</p><div className="settings-members"><table><thead><tr><th>用户</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody>{members.map(m=><tr key={m.user_id}><td>{m.email??'账号信息不可用'}</td><td>{roles[m.role]}</td><td>已加入</td><td>{owner&&m.role!=='owner'?<details><summary aria-label={`管理 ${m.email??'成员'}`}>⋯</summary><button className="secondary compact" onClick={()=>open(m)}>修改角色</button><button className="secondary compact danger-text" onClick={()=>open(m,true)}>移除成员</button></details>:m.role==='owner'?'所有者':'—'}</td></tr>)}</tbody></table></div></>}
 {(tab==='danger'||(hideNavigation&&tab==='general'))&&<><h2>危险操作</h2><section className="settings-danger"><h3>删除项目</h3><p>删除会永久移除项目及相关业务记录。当前尚未开放可靠的级联删除。</p>{owner?<button className="secondary danger-text" disabled>删除项目 · 暂不可用</button>:<p>仅项目所有者可执行危险操作。</p>}</section></>}
 </div></div><dialog onClose={()=>setDialogOpen(false)} ref={dialog} className="member-dialog" onCancel={e=>{e.stopPropagation();if(busy)e.preventDefault();}}><form onSubmit={e=>{e.preventDefault();void submitMember();}}><h2>{editing?(removing?'移除成员':'修改成员角色'):'添加已有账号'}</h2>{error&&<p role="alert">{error}</p>}{editing?<p>{editing.email}</p>:<label>邮箱<input type="email" autoFocus required value={email} onChange={e=>setEmail(e.target.value)} maxLength={254} disabled={busy}/></label>}{removing?<p>该成员将失去此项目的访问权限，其创建的数据会保留。</p>:<><label>项目角色<select value={role} onChange={e=>setRole(e.target.value)} disabled={busy}><option value="editor">编辑者</option><option value="viewer">查看者</option></select></label><p className="muted">{role==='editor'?'可修改项目内容、上传影像、创建 AOI / 视觉样例、运行任务和审核结果；不可管理成员。':'可查看地图、数据和结果，不可修改项目内容。'}</p></>}<div className="dialog-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>dialog.current?.close()}>取消</button><button className="secondary" disabled={busy}>{busy?'正在处理…':editing?(removing?'确认移除':'保存角色'):'添加成员'}</button></div></form></dialog></section>;
}
