"use client";
import {useId,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {manageAsset} from '../app/asset-actions';
export default function RasterActions({id,name,projectId,editable,onDetails,onRemoved}:{id:string;name:string;projectId:string;editable:boolean;onDetails:()=>void;onLocate:()=>void;onRemoved:()=>void}){
 const menuId=useId(),menu=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null),router=useRouter();const [operation,setOperation]=useState<'alias'|'unlink'|'delete'>('alias'),[value,setValue]=useState(name),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const open=(op:typeof operation)=>{menu.current?.hidePopover();setOperation(op);setValue(name);setError('');dialog.current?.showModal();};
 return <><button type="button" className="secondary object-more" aria-label={`${name} 的影像操作`} title="更多操作" popoverTarget={menuId} onClick={e=>{const rect=e.currentTarget.getBoundingClientRect();if(menu.current){menu.current.style.left=`${rect.left}px`;menu.current.style.top=`${Math.min(rect.bottom,window.innerHeight-250)}px`;}}}>⋯</button><div id={menuId} ref={menu} popover="auto" className="object-action-menu">{editable&&<button onClick={()=>open('alias')}>重命名</button>}<button onClick={()=>{menu.current?.hidePopover();onDetails();}}>查看详情</button><a href={`/api/rasters/${id}/download`}>下载</a>{editable&&<><button onClick={()=>open('unlink')}>从当前项目移除</button><button onClick={()=>open('delete')}>删除影像</button></>}</div><dialog ref={dialog} className="object-rename-dialog" aria-label="影像管理" onKeyDown={e=>e.stopPropagation()} onCancel={e=>{if(busy)e.preventDefault();}}><h3>{operation==='alias'?'重命名项目影像':operation==='unlink'?`从项目移除“${name}”？`:`删除影像“${name}”？`}</h3><p>{operation==='alias'?'只修改当前项目中的显示名称，不影响其他项目。':operation==='unlink'?'仅移除项目引用，保留原始影像、其他项目和历史任务。':'仅影像所有者或平台管理员可删除。请先移除所有项目引用；历史任务证据仍将保留。'}</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const result=await manageAsset(id,operation,value,projectId);if(result.error)setError(result.error);else{dialog.current?.close();if(operation!=='alias')onRemoved();router.refresh();}}catch{setError('操作失败，请重试。');}finally{setBusy(false);}}}>{operation==='alias'&&<label>项目显示名称<input required maxLength={255} value={value} onChange={e=>setValue(e.target.value)}/></label>}{error&&<p role="alert">{error}</p>}<div className="object-dialog-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>dialog.current?.close()}>取消</button><button className={operation==='alias'?'secondary':'danger'} disabled={busy||operation==='alias'&&!value.trim()}>{operation==='alias'?'保存':operation==='unlink'?'确认移除':'确认删除'}</button></div></form></dialog></>;
}
