"use client";
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {languageRequest} from '../app/control/models/language/actions';
export type AssistantContext={channel:'mock'|'worker';raster_id?:string;prompt_id?:string;aoi_id?:string;endpoint_id?:string;query_col?:number;query_row?:number;window_aoi_id?:string;selected_result?:string;last_job?:string;last_result?:string;last_user_goal?:string;current_map_center?:number[];current_map_bounds?:number[];current_zoom?:number;visible_layers?:string[];active_left_panel?:string};
type Named={id:string;name:string};
type UITool={action:string;id?:string;resource_kind?:string;job_id?:string;geometry?:unknown;visible?:boolean};
type State='READY'|'NEED_CLARIFICATION'|'NEED_CONFIRMATION'|'EXECUTING'|'COMPLETED'|'BLOCKED'|'ERROR';
type Answer={kind:string;conversation_state?:State;message:string;draft_id?:string;continuation_id?:string;confirmation_id?:string;labels?:Record<string,string>;plan?:string[];quality_note?:string;context_update?:AssistantContext;choices?:Named[];field?:string;ui_tool?:UITool;suggested_actions?:string[];job?:{id:string;status:string;progress:number}};
type Turn={role:'user'|'assistant';text:string};
const stateLabels:Record<State,string>={READY:'就绪',NEED_CLARIFICATION:'等待选择',NEED_CONFIRMATION:'等待确认',EXECUTING:'执行中',COMPLETED:'已完成',BLOCKED:'能力受限',ERROR:'需要处理'};
export default function TaskAssistant({projectId,editable,context,onContextChange,onPickWindow,getLiveContext,storageKey,onStatus,rasters,prompts,aois}:{projectId:string;editable:boolean;context:AssistantContext;onContextChange:(c:AssistantContext)=>void;onPickWindow:(rasterId:string,aoiId?:string)=>void;getLiveContext:()=>Partial<AssistantContext>;storageKey:string;onStatus:(s:string)=>void;rasters:{id:string;filename:string;status:string}[];prompts:Named[];aois:Named[]}){
 const router=useRouter();const [text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[answer,setAnswer]=useState<Answer|null>(null),[external,setExternal]=useState(false),[consent,setConsent]=useState(false),[history,setHistory]=useState<Turn[]>([]),[watchJob,setWatchJob]=useState<string|null>(null),[ready,setReady]=useState(false);
 const [mapPending,setMapPending]=useState<{answer:Answer;context:AssistantContext}|null>(null);const responseRef=useRef<HTMLDivElement>(null),contextRef=useRef(context);useEffect(()=>{contextRef.current=context;},[context]);
 const state:State=error?'ERROR':busy||watchJob?'EXECUTING':mapPending?'NEED_CLARIFICATION':answer?.conversation_state??'READY';
 useEffect(()=>{onStatus(busy&&!watchJob?'理解中':stateLabels[state]);},[state,busy,watchJob,onStatus]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{try{const raw=sessionStorage.getItem(storageKey);if(raw){const saved=JSON.parse(raw);setHistory(saved.history??[]);setAnswer(saved.answer??null);setWatchJob(saved.watchJob??null);setMapPending(saved.mapPending??null);if(saved.context)onContextChange(saved.context);}}catch{}setReady(true);});return()=>cancelAnimationFrame(frame);},[storageKey,onContextChange]);
 useEffect(()=>{if(ready)try{sessionStorage.setItem(storageKey,JSON.stringify({history,answer,watchJob,mapPending,context}));}catch{}},[ready,storageKey,history,answer,watchJob,mapPending,context]);
 useEffect(()=>{let active=true;languageRequest('/llm/availability',undefined,'GET').then(r=>{if(active&&r.data)setExternal(r.data.external);});return()=>{active=false;};},[]);
 function tool(action:UITool){window.dispatchEvent(new CustomEvent('workspace-agent-ui',{detail:action}));}
 function append(role:Turn['role'],value:string){setHistory(old=>[...old,{role,text:value}].slice(-30));}
 async function request(message:string,ctx:AssistantContext,continuation?:Answer,acceptSingleTile=false){setBusy(true);setError('');setAnswer(null);try{const r=await languageRequest(`/projects/${projectId}/assistant/agent`,{text:message,workspace_context:ctx,allow_external_metadata:consent,continuation_id:continuation?.continuation_id,accept_single_tile:acceptSingleTile});if(r.error)setError(r.error);else{const result=r.data as Answer;onContextChange(result.context_update??ctx);setAnswer(result);append('assistant',result.message);if(result.ui_tool)tool(result.ui_tool);}}finally{setBusy(false);setConsent(false);}}
 async function confirm(){if(!answer?.draft_id)return;append('user','开始测试');setBusy(true);setError('');try{const r=await languageRequest(`/projects/${projectId}/assistant/confirm`,{draft_id:answer.draft_id,confirmed:true});if(r.error)setError(r.error);else{onContextChange({...contextRef.current,last_job:r.data.id});setWatchJob(r.data.id);setAnswer({kind:'status',conversation_state:'EXECUTING',message:'已开始测试，任务将在后台继续运行。'});append('assistant','已开始测试，任务将在后台继续运行。');router.refresh();}}finally{setBusy(false);}}
 async function cancelJob(){if(!answer?.confirmation_id)return;setBusy(true);try{const r=await languageRequest(`/projects/${projectId}/assistant/cancel`,{confirmation_id:answer.confirmation_id,confirmed:true});if(r.error)setError(r.error);else{setAnswer({kind:'status',conversation_state:'COMPLETED',message:'任务已取消。'});append('assistant','任务已取消。');setWatchJob(null);router.refresh();}}finally{setBusy(false);}}
 function discard(){setAnswer(null);setMapPending(null);append('assistant','已取消待处理操作，没有提交新的任务。');}
 async function choose(candidate:Named){if(!answer?.field)return;append('user',candidate.name);const pending={...(answer.context_update??contextRef.current),[answer.field]:candidate.id};await request(candidate.name,pending,answer);}
 async function send(message=text){if(!message.trim())return;setText('');if(/^(开始|开始测试|确认|执行)[。！!]?$/u.test(message.trim())){if(answer?.draft_id){await confirm();return;}if(answer?.confirmation_id){await cancelJob();return;}}
 if(/^(取消|不用了)[。！!]?$/u.test(message.trim())&&!watchJob){append('user',message);discard();return;}
 const candidate=answer?.choices?.find(c=>c.name===message.trim());if(candidate){await choose(candidate);return;}
 append('user',message);await request(message,{...contextRef.current,...Object.fromEntries(Object.entries(getLiveContext()).filter(([,value])=>value!==undefined))});}
 function chooseWindow(){if(!answer)return;const ctx=answer.context_update??contextRef.current;if(!ctx.raster_id)return;setMapPending({answer,context:ctx});append('assistant','请选择地图上的测试位置，原目标和已确定资源保持不变。');onPickWindow(ctx.raster_id,ctx.aoi_id);}
 useEffect(()=>{const selected=(event:Event)=>{if(!mapPending)return;const selection=(event as CustomEvent).detail;if(selection.raster_id!==mapPending.context.raster_id)return;const next={...mapPending.context,query_col:selection.query_col,query_row:selection.query_row,window_aoi_id:selection.aoi_id??undefined};setMapPending(null);void request('已选择地图测试位置',next,mapPending.answer,mapPending.answer.kind==='capability_unavailable');};const cancelled=()=>{setMapPending(null);append('assistant','已取消地图选点。原目标保留，可继续选择。');};window.addEventListener('workspace-tile-selected',selected);window.addEventListener('workspace-agent-map-cancelled',cancelled);return()=>{window.removeEventListener('workspace-tile-selected',selected);window.removeEventListener('workspace-agent-map-cancelled',cancelled);};});
 useEffect(()=>{responseRef.current?.scrollIntoView({block:'nearest'});},[answer,history]);
 useEffect(()=>{if(!watchJob)return;let active=true;let terminal=false;const tick=async()=>{if(terminal)return;const r=await languageRequest(`/projects/${projectId}/assistant/observe`,{job_id:watchJob});if(!active)return;if(r.error){setError(r.error);return;}const result=r.data as Answer;const done=result.job&&!['queued','running'].includes(result.job.status);setAnswer(current=>current&&current.kind!=='status'?current:{...result,kind:'status',conversation_state:done?(result.job?.status==='failed'?'ERROR':'COMPLETED'):'EXECUTING'});if(done){terminal=true;setWatchJob(null);append('assistant',result.message);if(result.ui_tool){tool(result.ui_tool);onContextChange({...contextRef.current,last_result:result.ui_tool.id,selected_result:result.ui_tool.id});}router.refresh();}};void tick();const timer=setInterval(()=>void tick(),3000);return()=>{active=false;clearInterval(timer);};},[watchJob,projectId,router,onContextChange]);
 function reset(){if(watchJob)return;setHistory([]);setAnswer(null);setError('');setText('');setMapPending(null);onContextChange({channel:'worker',...getLiveContext(),last_job:undefined,last_result:undefined,last_user_goal:undefined,query_col:undefined,query_row:undefined});}
 const live={...context,...Object.fromEntries(Object.entries(getLiveContext()).filter(([,value])=>value!==undefined))};const summary=[rasters.find(r=>r.id===live.raster_id)?.filename,aois.find(a=>a.id===live.aoi_id)?.name,prompts.find(p=>p.id===live.prompt_id)?.name].filter(Boolean).join(' · ')||'自动读取地图与当前选择';
 return <section className="task-assistant" data-conversation-state={state}><div className="agent-context-line"><span title={summary}>{summary}</span><button className="secondary" disabled={busy||!!watchJob} onClick={reset}>新建对话</button></div><div className="agent-conversation" role="log" aria-label="对话记录">{history.length===0&&<p className="muted">告诉我想做什么。我会读取当前选择，必要时追问，运行模型前请你确认。</p>}{history.map((turn,i)=><div key={i} className={'agent-turn '+turn.role}><small>{turn.role==='user'?'你':'GeoAI'}</small><p>{turn.text}</p></div>)}<div ref={responseRef}>{error&&<p role="alert">{error}</p>}{answer&&<div className="assistant-answer">
 {watchJob&&<p role="status">{answer.message}</p>}{answer.labels&&<dl>{Object.entries(answer.labels).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>}{answer.quality_note&&<small>{answer.quality_note}</small>}
 {answer.choices?.length?<div className="agent-choice-buttons" aria-label="请选择">{answer.choices.map(c=><button key={c.id} className="secondary" disabled={busy} onClick={()=>void choose(c)}>{c.name}</button>)}</div>:null}
 {answer.suggested_actions?.includes('select_window')&&<><button className="secondary" disabled={busy} onClick={chooseWindow}>在地图上选择测试位置</button><button className="secondary" onClick={discard}>取消</button></>}
 {answer.suggested_actions?.includes('check_compute')&&<Link href="/control/models">查看节点状态</Link>}
 {answer.suggested_actions?.includes('show_result')&&<button className="secondary" onClick={()=>void send('显示刚才结果')}>查看最近结果</button>}
 {answer.suggested_actions?.includes('create_prompt')&&<button className="secondary" disabled={!editable} onClick={()=>tool({action:'create_prompt'})}>绘制新样例</button>}
 {answer.draft_id&&<><p>此计划已固定资源。更改地图选择不会改变本次待确认任务。</p><button disabled={!editable||busy} onClick={()=>void confirm()}>开始测试</button><button className="secondary" disabled={busy} onClick={discard}>取消</button></>}
 {answer.kind==='cancel_confirmation'&&<><button className="danger" disabled={!editable||busy} onClick={()=>void cancelJob()}>确认取消任务</button><button className="secondary" onClick={discard}>继续任务</button></>}
 </div>}</div></div><form onSubmit={e=>{e.preventDefault();void send();}}><label className="sr-only" htmlFor="agent-message">想做什么？</label><textarea id="agent-message" value={text} maxLength={2000} rows={2} disabled={busy} onChange={e=>{setText(e.target.value);setConsent(false);}} placeholder="用这个样例测试这里…"/>{external&&<label className="inline-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>同意本次向已配置云端发送文本和资源名称</label>}<button className="secondary" disabled={busy||!text.trim()||external&&!consent}>{busy?'理解中…':'发送'}</button></form></section>;
}
