"use client";
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {languageRequest} from '../app/control/models/language/actions';
type Answer={kind:string;message:string;draft_id?:string;labels?:Record<string,string>;jobs?:{id:string;status:string;progress:number}[];runtime_ms:number;llm_model:string};
export default function TaskAssistant({projectId,editable,onConfirmed}:{projectId:string;editable:boolean;onConfirmed?:()=>void}){
 const router=useRouter();const [text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[answer,setAnswer]=useState<Answer|null>(null),[external,setExternal]=useState(false),[allow,setAllow]=useState(false);
 useEffect(()=>{let active=true;languageRequest('/llm/availability',undefined,'GET').then(r=>{if(active&&r.data)setExternal(r.data.external);});return()=>{active=false;};},[]);
 async function plan(){const consent=allow;setAllow(false);setBusy(true);setError('');setAnswer(null);try{const r=await languageRequest(`/projects/${projectId}/assistant/plan`,{text,allow_external_metadata:consent});if(r.error)setError(r.error);else setAnswer(r.data);}finally{setBusy(false);}}
 async function confirm(){if(!answer?.draft_id)return;setBusy(true);setError('');try{const r=await languageRequest(`/projects/${projectId}/assistant/confirm`,{draft_id:answer.draft_id,confirmed:true});if(r.error)setError(r.error);else{setText('');setAnswer(null);onConfirmed?.();router.push(`/projects/${projectId}/workspace?job=${r.data.id}&message=${encodeURIComponent('已确认并创建任务，任务将在后台继续运行。')}`);router.refresh();}}finally{setBusy(false);}}
 return <section className="task-assistant"><h3>自然语言任务助手</h3><p>描述目标，核对草案后再运行。原有手动操作不受影响。</p><form onSubmit={e=>{e.preventDefault();void plan();}}><label>任务描述<textarea value={text} maxLength={2000} rows={5} disabled={busy} onChange={e=>{setText(e.target.value);setAnswer(null);setAllow(false);}} placeholder="例如：查看当前项目任务状态；或使用某视觉样例在影像的列 0、行 0 运行单瓦片提取。"/></label>{external&&<label className="inline-check"><input type="checkbox" checked={allow} onChange={e=>setAllow(e.target.checked)}/>同意本次将文本与资源元数据发送到已配置的云端服务</label>}<button className="secondary" disabled={busy||!text.trim()||external&&!allow}>{busy?'正在处理…':'生成任务草案'}</button></form>{error&&<p role="alert" className="notice">{error}</p>}{answer&&<div className="assistant-answer"><p>{answer.message}</p>{answer.labels&&<dl>{Object.entries(answer.labels).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>}{answer.jobs?.map((job,i)=><p key={job.id}>任务 {i+1} · {job.status} · {Math.round(job.progress)}%</p>)}{answer.kind==='status'&&!answer.jobs?.length&&<p>暂无任务。</p>}<small>{answer.llm_model} · {answer.runtime_ms} ms</small>{answer.draft_id&&<><p className="notice">LLM 仅填写参数，不参与像素分割。请确认样例、影像、通道与窗口正确。</p><button disabled={!editable||busy} onClick={()=>void confirm()}>确认并创建任务</button><button className="secondary" disabled={busy} onClick={()=>setAnswer(null)}>丢弃草案</button></>}</div>}<small>当前支持已保存视觉样例及单瓦片推理；不支持自动标注、全图扫描、语言排除条件或自动审核。</small></section>;
}
