"use client";
import { useEffect, useState } from 'react';
import { createTileJob } from '../app/actions';
import PendingSubmit from './pending-submit';
import type { VisualPrompt, Aoi } from './project-map';
import type { RasterAsset } from '../lib/session';
export type AvailableEndpoint={id:string;name:string;model_release_id:string;model_name:string;model_version:string;usage_policy:string;config_revision:number;health_status:string};
export default function TileExtractionForm({projectId,prompts,rasters,aois,endpoints,idempotencyKey}:{projectId:string;prompts:VisualPrompt[];aois:Aoi[];rasters:RasterAsset[];endpoints:AvailableEndpoint[];idempotencyKey:string}) {
 const usable=rasters.filter(r=>r.status==='ready'&&(r.width??0)>=512&&(r.height??0)>=512&&(r.bands??0)>=3);
 const supports=prompts.filter(p=>usable.some(r=>r.id===p.raster_asset_id));
 const [step,setStep]=useState(0);const [aoiId,setAoiId]=useState(aois.length===1?aois[0].id:'');
 const [endpointId,setEndpointId]=useState(endpoints[0]?.id??'');
 const [rasterId,setRasterId]=useState(usable[0]?.id??'');
 const [promptId,setPromptId]=useState(supports[0]?.id??'');
 const [col,setCol]=useState('');const [row,setRow]=useState('');const [seed,setSeed]=useState('57');
 const [selecting,setSelecting]=useState(false);
 useEffect(()=>{const receive=(event:Event)=>{const d=(event as CustomEvent).detail;if(d.raster_id===rasterId){setAoiId(d.aoi_id??'');setCol(String(d.query_col));setRow(String(d.query_row));setSelecting(false);}};window.addEventListener('workspace-tile-selected',receive);return()=>window.removeEventListener('workspace-tile-selected',receive);},[rasterId]);
 const endpoint=endpoints.find(e=>e.id===endpointId);const raster=usable.find(r=>r.id===rasterId);const prompt=supports.find(p=>p.id===promptId);
 const windowValid=!!raster&&col!==''&&row!==''&&[Number(col),Number(row)].every(n=>Number.isInteger(n)&&n>=0)&&Number(col)+512<=raster.width!&&Number(row)+512<=raster.height!;
 const seedValid=seed!==''&&Number.isInteger(Number(seed))&&Number(seed)>=0&&Number(seed)<=4294967295;
 const ready=[!!raster,!!prompt,windowValid,!!endpoint,!!raster&&!!prompt&&windowValid&&!!endpoint&&seedValid];
 return <form action={createTileJob}><h3>样例引导提取</h3><p>一个视觉样例，定义提取目标。当前执行单个原始分辨率 Tile。</p><ol className="extraction-steps">{['目标影像','Visual Prompt','模型输入窗口','计算模型','确认与运行'].map((label,i)=><li key={label} aria-current={step===i?'step':undefined}><button type="button" className="secondary compact" disabled={i>step+1||i>0&&!ready.slice(0,i).every(Boolean)} onClick={()=>setStep(i)}>{ready[i]&&i<step?'✓ ':''}{i+1}. {label}</button></li>)}</ol>
 <input type="hidden" name="project_id" value={projectId}/><input type="hidden" name="idempotency_key" value={idempotencyKey}/><input type="hidden" name="model_release_id" value={endpoint?.model_release_id??''}/><input type="hidden" name="endpoint_revision" value={endpoint?.config_revision??''}/><input type="hidden" name="raster_asset_id" value={rasterId}/><input type="hidden" name="prompt_id" value={promptId}/><input type="hidden" name="model_endpoint_id" value={endpointId}/><input type="hidden" name="aoi_id" value={aoiId}/><input type="hidden" name="query_col" value={col}/><input type="hidden" name="query_row" value={row}/><input type="hidden" name="seed" value={seed}/>
 {step===0&&<><label>目标影像<select value={rasterId} onChange={e=>{setRasterId(e.target.value);setCol('');setRow('');}}>{usable.map(r=><option key={r.id} value={r.id}>{r.filename} · {r.width} × {r.height}</option>)}</select></label>{!usable.length&&<p role="status">请先上传至少 512 × 512 的 RGB 影像，等待处理完成。</p>}</>}
 {step===1&&<><label>已保存样例<select value={promptId} onChange={e=>setPromptId(e.target.value)}>{supports.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><p>样例可来自项目中的另一景影像。</p>{!supports.length&&<p role="status">请在地图创建 Visual Prompt。样例源影像也需至少 512 × 512。</p>}</>}
 {step===2&&<><label>有效分析范围<select value={aoiId} onChange={e=>{setAoiId(e.target.value);setCol('');setRow('');}}><option value="">使用地图当前 AOI（未选时仅测试窗口）</option>{aois.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button type="button" className="secondary" disabled={!raster} onClick={()=>{setSelecting(true);window.dispatchEvent(new CustomEvent('workspace-select-tile',{detail:{rasterId,aoiId:aoiId||undefined,origin:'manual'}}));}}>在地图上选择测试位置</button><p>{selecting?'在地图影像上点击测试位置，Esc 取消。':windowValid?'已选择模型输入窗口 · 结果仅保留 AOI 内部分':'尚未选择测试区域'}</p><small>绿色 AOI 是有效分析范围；蓝色虚线是模型输入窗口，可以大于 AOI。</small></>}
 {step===3&&<><label>模型与计算服务器<select value={endpointId} onChange={e=>setEndpointId(e.target.value)}>{endpoints.map(e=><option key={e.id} value={e.id}>{e.model_name} · {e.name}</option>)}</select></label>{endpoint&&<p><span className="badge">{endpoint.usage_policy==='research_only'?'RESEARCH ONLY':endpoint.usage_policy==='internal_only'?'SYNTHETIC TEST':'PRODUCTION'}</span> · {endpoint.health_status}</p>}{!endpoints.length&&<p role="status">暂无可用端点。管理员需配置权重身份并启用服务器；GPU 未就绪时可继续使用 Mock 工作流。</p>}</>}
 {step===4&&<><dl><dt>目标影像</dt><dd>{raster?.filename}</dd><dt>Visual Prompt</dt><dd>{prompt?.name}</dd><dt>模型输入窗口</dt><dd>地图选择 · 512 × 512 原分辨率像素</dd><dt>模型</dt><dd>{endpoint?.model_name} · {endpoint?.model_version}</dd><dt>计算服务器</dt><dd>{endpoint?.name} · {endpoint?.health_status}</dd></dl>{endpoint?.usage_policy!=='commercial'&&<p className="notice">{endpoint?.usage_policy==='research_only'?'仅研究用途。':'合成测试，不代表真实模型识别。'}</p>}<details><summary>Advanced Settings</summary><label>Seed<input type="number" min={0} max={4294967295} value={seed} onChange={e=>setSeed(e.target.value)}/></label><small>样例 polygon 必须完整落在一个源分辨率 512 × 512 窗口内。</small></details><PendingSubmit disabled={!ready[4]} pendingLabel="正在创建任务…">运行单 Tile 提取</PendingSubmit></>}
 <div className="draw-actions">{step>0&&<button type="button" className="secondary compact" onClick={()=>setStep(step-1)}>上一步</button>}{step<4&&<button type="button" className="secondary compact" disabled={!ready[step]} onClick={()=>setStep(step+1)}>下一步</button>}</div></form>;
}
