"use client";
import { useEffect, useState } from 'react';
import { createTileJob } from '../app/actions';
import {languageRequest} from '../app/control/models/language/actions';
import PendingSubmit from './pending-submit';
import type { VisualPrompt, Aoi } from './project-map';
import type { RasterAsset } from '../lib/session';
export type AvailableEndpoint={id:string;name:string;model_release_id:string;model_name:string;model_version:string;usage_policy:string;config_revision:number;health_status:string};
export default function TileExtractionForm({projectId,prompts,rasters,aois,endpoints,idempotencyKey,initialContext}:{initialContext?:{raster_id?:string;aoi_id?:string;prompt_id?:string};projectId:string;prompts:VisualPrompt[];aois:Aoi[];rasters:RasterAsset[];endpoints:AvailableEndpoint[];idempotencyKey:string}) {
 const usable=rasters.filter(r=>r.status==='ready'&&(r.width??0)>=512&&(r.height??0)>=512&&(r.bands??0)>=3);
 const supports=prompts.filter(p=>usable.some(r=>r.id===p.raster_asset_id));
 const [step,setStep]=useState(0);const [aoiId,setAoiId]=useState(initialContext?.aoi_id??(aois.length===1?aois[0].id:''));
 const [endpointId,setEndpointId]=useState(endpoints[0]?.id??'');
 const [rasterId,setRasterId]=useState(initialContext?.raster_id??usable[0]?.id??'');
 const [promptId,setPromptId]=useState(initialContext?.prompt_id??supports[0]?.id??'');
 const [col,setCol]=useState('');const [row,setRow]=useState('');const [seed,setSeed]=useState('57');
 const [selecting,setSelecting]=useState(false),[scope,setScope]=useState<'full_aoi'|'single_tile'>('full_aoi'),[message,setMessage]=useState(''),[checking,setChecking]=useState(false),[windowKey,setWindowKey]=useState('');
 const identity=`${rasterId}:${aoiId}:${scope}`;
 useEffect(()=>{let active=true;const timer=setTimeout(()=>{window.dispatchEvent(new Event('workspace-clear-tile'));setCol('');setRow('');setWindowKey('');setMessage('');if(scope!=='full_aoi'||!aoiId||!rasterId){setChecking(false);return;}setChecking(true);languageRequest(`/projects/${projectId}/assistant/coverage`,{raster_id:rasterId,aoi_id:aoiId}).then(response=>{if(!active)return;setChecking(false);if(response.error){setMessage(response.error);return;}setMessage(response.data.message);if(response.data.available){setCol(String(response.data.query_col));setRow(String(response.data.query_row));setWindowKey(`${rasterId}:${aoiId}:full_aoi`);window.dispatchEvent(new CustomEvent('workspace-auto-tile',{detail:response.data}));}});},0);return()=>{active=false;clearTimeout(timer);window.dispatchEvent(new Event('workspace-clear-tile'));};},[projectId,rasterId,aoiId,scope]);
 useEffect(()=>{const failed=(event:Event)=>{setSelecting(false);setMessage((event as CustomEvent).detail.message);};const created=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail.kind==='aoi'){setAoiId(detail.id);setStep(2);}};const cancelled=()=>{setSelecting(false);setMessage('已取消地图选择。');};window.addEventListener('workspace-tile-selection-error',failed);window.addEventListener('workspace-resource-created',created);window.addEventListener('workspace-tile-selection-cancelled',cancelled);return()=>{window.removeEventListener('workspace-tile-selection-error',failed);window.removeEventListener('workspace-resource-created',created);window.removeEventListener('workspace-tile-selection-cancelled',cancelled);};},[]);
 useEffect(()=>{const receive=(event:Event)=>{const d=(event as CustomEvent).detail;if(d.raster_id===rasterId&&scope==='single_tile'){setAoiId(d.aoi_id??'');setCol(String(d.query_col));setRow(String(d.query_row));setWindowKey(`${rasterId}:${d.aoi_id??''}:single_tile`);setSelecting(false);setMessage('测试位置已确定，可以继续。');}};window.addEventListener('workspace-tile-selected',receive);return()=>window.removeEventListener('workspace-tile-selected',receive);},[rasterId,scope]);
 const endpoint=endpoints.find(e=>e.id===endpointId);const raster=usable.find(r=>r.id===rasterId);const prompt=supports.find(p=>p.id===promptId);
 const windowValid=windowKey===identity&&!!raster&&col!==''&&row!==''&&[Number(col),Number(row)].every(n=>Number.isInteger(n)&&n>=0)&&Number(col)+512<=raster.width!&&Number(row)+512<=raster.height!;
 const seedValid=seed!==''&&Number.isInteger(Number(seed))&&Number(seed)>=0&&Number(seed)<=4294967295;
 const ready=[!!raster,!!prompt,windowValid,!!endpoint,!!raster&&!!prompt&&windowValid&&!!endpoint&&seedValid];
 return <form action={createTileJob}><h3>样例引导提取</h3><p>选择目标影像与视觉样例。小范围可一次完整分析，也可在地图上指定局部测试位置。</p><ol className="extraction-steps">{['目标影像','视觉样例','分析范围','计算模型','确认与运行'].map((label,i)=><li key={label} aria-current={step===i?'step':undefined}><button type="button" className="secondary compact" disabled={i>step+1||i>0&&!ready.slice(0,i).every(Boolean)} onClick={()=>setStep(i)}>{ready[i]&&i<step?'✓ ':''}{i+1}. {label}</button></li>)}</ol>
 <input type="hidden" name="execution_scope" value={scope}/><input type="hidden" name="project_id" value={projectId}/><input type="hidden" name="idempotency_key" value={idempotencyKey}/><input type="hidden" name="model_release_id" value={endpoint?.model_release_id??''}/><input type="hidden" name="endpoint_revision" value={endpoint?.config_revision??''}/><input type="hidden" name="raster_asset_id" value={rasterId}/><input type="hidden" name="prompt_id" value={promptId}/><input type="hidden" name="model_endpoint_id" value={endpointId}/><input type="hidden" name="aoi_id" value={aoiId}/><input type="hidden" name="query_col" value={col}/><input type="hidden" name="query_row" value={row}/><input type="hidden" name="seed" value={seed}/>
 {step===0&&<><label>目标影像<select value={rasterId} onChange={e=>{setRasterId(e.target.value);setCol('');setRow('');window.dispatchEvent(new CustomEvent('workspace-target-raster',{detail:{rasterId:e.target.value}}));}}>{usable.map(r=><option key={r.id} value={r.id}>{r.filename} · {r.width} × {r.height}</option>)}</select></label>{!usable.length&&<p role="status">请先上传至少 512 × 512 的 RGB 影像，等待处理完成。</p>}</>}
 {step===1&&<><label>已保存样例<select value={promptId} onChange={e=>setPromptId(e.target.value)}>{supports.map(p=><option key={p.id} value={p.id}>{p.name} · {rasters.find(r=>r.id===p.raster_asset_id)?.filename??'已保存来源'}</option>)}</select></label><p>样例可来自项目中的另一景影像。</p>{!supports.length&&<p role="status">请在地图创建 Visual Prompt。样例源影像也需至少 512 × 512。</p>}</>}
 {step===2&&<><div className="draw-actions"><button type="button" className="secondary" aria-pressed={scope==='full_aoi'} onClick={()=>{setScope('full_aoi');setSelecting(false);}}>分析整个 AOI</button><button type="button" className="secondary" aria-pressed={scope==='single_tile'} onClick={()=>setScope('single_tile')}>局部测试</button></div><label>有效分析范围<select value={aoiId} onChange={e=>{setAoiId(e.target.value);setCol('');setRow('');}}><option value="">{scope==='full_aoi'?'请选择 AOI':'不限定 AOI，仅测试所选位置'}</option>{aois.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{scope==='full_aoi'&&!aoiId&&<p>先选择已有范围，或在目标影像上创建 AOI。</p>}<button type="button" className="secondary" onClick={()=>window.dispatchEvent(new CustomEvent('workspace-agent-ui',{detail:{action:'create_aoi',origin:'manual',raster_id:rasterId}}))}>在目标影像上绘制 AOI</button>{scope==='single_tile'&&<button type="button" className="secondary" disabled={!raster||selecting} onClick={()=>{setSelecting(true);setMessage('请在目标影像上点击测试位置。');window.dispatchEvent(new CustomEvent('workspace-select-tile',{detail:{rasterId,aoiId:aoiId||null,origin:'manual'}}));}}>{selecting?'正在等待地图选择…':'在地图上选择测试位置'}</button>}{selecting&&<button type="button" className="secondary" onClick={()=>window.dispatchEvent(new Event('workspace-cancel-tile-selection'))}>取消选点</button>}<p role="status">{checking?'正在检查当前范围…':message|| (scope==='single_tile'?'请选择一个位置进行测试。':'')}</p>{scope==='full_aoi'&&aoiId&&!checking&&!windowValid&&message&&<button type="button" className="secondary" onClick={()=>setScope('single_tile')}>改为局部测试</button>}<small>绿色：AOI / 有效分析范围。蓝色虚线：模型输入窗口。窗口外沿可超出 AOI，成果仅保留 AOI 内部分。</small></> }
 {step===3&&<><label>模型与计算服务器<select value={endpointId} onChange={e=>setEndpointId(e.target.value)}>{endpoints.map(e=><option key={e.id} value={e.id}>{e.model_name} · {e.name}</option>)}</select></label>{endpoint&&<p><span className="badge">{endpoint.usage_policy==='research_only'?'RESEARCH ONLY':endpoint.usage_policy==='internal_only'?'SYNTHETIC TEST':'PRODUCTION'}</span> · {endpoint.health_status}</p>}{!endpoints.length&&<p role="status">暂无可用端点。管理员需配置权重身份并启用服务器；GPU 未就绪时可继续使用 Mock 工作流。</p>}</>}
 {step===4&&<><dl><dt>目标影像</dt><dd>{raster?.filename}</dd><dt>视觉样例</dt><dd>{prompt?.name}</dd><dt>模型输入窗口</dt><dd>{scope==='full_aoi'?'自动覆盖整个 AOI':'地图选定的局部测试'}</dd><dt>模型</dt><dd>{endpoint?.model_name} · {endpoint?.model_version}</dd><dt>计算服务器</dt><dd>{endpoint?.name} · {endpoint?.health_status}</dd></dl>{endpoint?.usage_policy!=='commercial'&&<p className="notice">{endpoint?.usage_policy==='research_only'?'仅研究用途。':'合成测试，不代表真实模型识别。'}</p>}<details><summary>高级设置</summary><label>Seed<input type="number" min={0} max={4294967295} value={seed} onChange={e=>setSeed(e.target.value)}/></label><small>样例 polygon 必须完整落在一个源分辨率 512 × 512 窗口内。</small></details><PendingSubmit disabled={!ready[4]} pendingLabel="正在创建任务…">{scope==='full_aoi'?'分析整个 AOI':'运行局部测试'}</PendingSubmit></>}
 <div className="draw-actions">{step>0&&<button type="button" className="secondary compact" onClick={()=>setStep(step-1)}>上一步</button>}{step<4&&<button type="button" className="secondary compact" disabled={!ready[step]} onClick={()=>setStep(step+1)}>下一步</button>}</div></form>;
}
