"use client";
import {useEffect,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import type {Project} from '../lib/session';
import {workspaceProjects} from '../app/projects/navigation-actions';
export default function WorkspaceNavigation({geometryDirty,running,projectId}:{geometryDirty:boolean;running:boolean;projectId:string}){
 const router=useRouter();const params=useSearchParams();const previousURL=useRef(`/projects/${projectId}/workspace`);useEffect(()=>{previousURL.current=`/projects/${projectId}/workspace`+(params.size?'?'+params.toString():'');},[params,projectId]);const guard=useRef<HTMLDialogElement>(null),picker=useRef<HTMLDialogElement>(null);const pending=useRef<(()=>void)|null>(null);const fields=useRef(new Map<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement,{initial:string;form:HTMLFormElement;last:string}>());const settingsDirty=useRef(false);const [projects,setProjects]=useState<Project[]>([]),[error,setError]=useState('');
 function value(el:HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement){return el instanceof HTMLInputElement&&el.type==='checkbox'?String(el.checked):el.value;}
 function dirty(){return geometryDirty||settingsDirty.current||[...fields.current].some(([el,state])=>state.form.isConnected&&(el.isConnected?value(el):state.last)!==state.initial);}
 useEffect(()=>{const remember=(e:Event)=>{const el=e.target;if((el instanceof HTMLInputElement||el instanceof HTMLTextAreaElement||el instanceof HTMLSelectElement)&&el.form&&!el.closest('.project-settings')){const previous=fields.current.get(el);if(previous)previous.last=value(el);else fields.current.set(el,{form:el.form,initial:el instanceof HTMLSelectElement?[...el.options].find(o=>o.defaultSelected)?.value??el.options[0]?.value??'':el instanceof HTMLInputElement&&el.type==='checkbox'?String(el.defaultChecked):el.defaultValue,last:value(el)});}};const settingsChanged=(event:Event)=>{settingsDirty.current=(event as CustomEvent<boolean>).detail;};const ask=(action:()=>void)=>{if(dirty()){pending.current=action;guard.current?.showModal();}else action();};const click=(event:MouseEvent)=>{const a=(event.target as HTMLElement).closest('a');if(!a||event.defaultPrevented||a.download||a.target==='_blank')return;const target=new URL(a.href,location.href);if(target.pathname===location.pathname||target.pathname.startsWith('/api/'))return;event.preventDefault();event.stopImmediatePropagation();ask(()=>router.push(target.pathname+target.search));};const unload=(event:BeforeUnloadEvent)=>{if(dirty()){event.preventDefault();event.returnValue='';}};const switchProject=()=>{picker.current?.showModal();workspaceProjects().then(setProjects).catch(()=>setError('无法读取项目，请重试。'));};const beforePop=(event:PopStateEvent)=>{if((location.pathname!==`/projects/${projectId}/workspace`||settingsDirty.current)&&dirty()){const target=location.pathname+location.search;event.stopImmediatePropagation();history.pushState(history.state,'',previousURL.current);pending.current=()=>router.push(target);guard.current?.showModal();}};
 const navigation=(window as Window&{navigation?:EventTarget}).navigation;const beforeNavigate=(event:Event)=>{const nav=event as Event&{navigationType?:string;destination?:{url:string}};if(nav.navigationType!=='traverse'||!nav.destination||!dirty())return;const target=new URL(nav.destination.url);if(target.pathname===location.pathname&&!settingsDirty.current)return;if(event.cancelable){event.preventDefault();pending.current=()=>{if(target.pathname===location.pathname)history.pushState(null,'',target.href);else router.push(target.pathname+target.search);};guard.current?.showModal();}};navigation?.addEventListener('navigate',beforeNavigate);
 window.addEventListener('workspace-settings-dirty',settingsChanged);document.addEventListener('focusin',remember,true);document.addEventListener('input',remember,true);document.addEventListener('click',click,true);window.addEventListener('beforeunload',unload);window.addEventListener('popstate',beforePop,true);window.addEventListener('workspace-switch',switchProject);return()=>{navigation?.removeEventListener('navigate',beforeNavigate);window.removeEventListener('workspace-settings-dirty',settingsChanged);document.removeEventListener('focusin',remember,true);document.removeEventListener('input',remember,true);document.removeEventListener('click',click,true);window.removeEventListener('beforeunload',unload);window.removeEventListener('popstate',beforePop,true);window.removeEventListener('workspace-switch',switchProject);};});
 return <><dialog ref={guard} className="member-dialog workspace-guard" onKeyDown={e=>e.stopPropagation()}><h2>当前工作区有未保存更改</h2><p>离开将丢弃未保存的绘制与表单草稿。</p>{running&&<p>任务将在后台继续运行。</p>}<div className="dialog-actions"><button className="secondary" onClick={()=>{pending.current=null;guard.current?.close();}}>继续工作</button><button onClick={()=>{guard.current?.close();pending.current?.();pending.current=null;}}>放弃未保存更改并离开</button></div></dialog><dialog ref={picker} className="member-dialog" onKeyDown={e=>e.stopPropagation()}><h2>切换项目</h2>{error&&<p role="alert">{error}</p>}<div className="workspace-switch-list">{projects.filter(p=>p.id!==projectId).map(p=><a key={p.id} href={`/projects/${p.id}/workspace`}>{p.name}</a>)}</div>{projects.length===1&&<p>暂无其他可访问项目。</p>}<button className="secondary" onClick={()=>picker.current?.close()}>取消</button></dialog>{running&&<span className="muted">任务将在后台继续运行</span>}</>;
}
