import Link from 'next/link';
import { notFound } from 'next/navigation';
import { api, ApiError, type Project } from '../../../lib/session';
import { editProject, manageMember } from '../../actions';
const labels: Record<string,string> = { owner: '所有者', editor: '编辑者', viewer: '查看者' };
export default async function ProjectPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ message?: string }> }) {
 const { id } = await params; if (!/^[0-9a-f-]{36}$/i.test(id)) notFound();
 let project: Project;
 try { project = await api<Project>(`/projects/${id}`); } catch (error) { if (error instanceof ApiError && error.status === 404) notFound(); throw error; }
 const { message } = await searchParams; const owner = project.my_role === 'owner'; const edit = owner || project.my_role === 'editor';
 return <><Link href="/projects">← 所有项目</Link><div className="page-heading"><span className="badge">{labels[project.my_role]}</span><h1>{project.name}</h1><p className="muted">{project.description || '为项目添加描述，让团队了解目标。'}</p></div>{message && <p className="notice" role="status">{message}</p>}<div className="project-grid"><section className="card"><h2>项目信息</h2><form action={editProject}><input type="hidden" name="project_id" value={id}/><label>项目名称<input name="name" defaultValue={project.name} required maxLength={120} disabled={!edit}/></label><label>项目描述<textarea name="description" defaultValue={project.description} maxLength={2000} rows={5} disabled={!edit}/></label>{edit && <button>保存修改</button>}</form></section><section className="card"><h2>项目成员</h2><div className="member"><code>{project.owner_id}</code><span className="badge">所有者</span></div>{project.members.map(m => <div className="member" key={m.user_id}><code>{m.user_id}</code>{owner ? <form action={manageMember}><input type="hidden" name="project_id" value={id}/><input type="hidden" name="user_id" value={m.user_id}/><select name="role" aria-label="成员角色" defaultValue={m.role}><option value="viewer">查看者</option><option value="editor">编辑者</option></select><button className="secondary compact" name="mode" value="change">更新</button><button className="secondary compact" name="mode" value="remove">移除</button></form> : <span className="badge">{labels[m.role]}</span>}</div>)}{owner && <form action={manageMember} className="member-form"><h3>添加已有账号</h3><input type="hidden" name="project_id" value={id}/><label>用户 ID<input name="user_id" required placeholder="对方在项目列表中显示的账号 ID"/></label><label>项目角色<select name="role" defaultValue="viewer"><option value="viewer">查看者 · 仅查看</option><option value="editor">编辑者 · 可以修改项目内容</option></select></label><button name="mode" value="add">添加成员</button></form>}</section></div></>;
}
